spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  webflux:
    multipart:
      max-in-memory-size: 512KB
      max-parts: 3
      max-disk-usage-per-part: 1024KB
      max-headers-size: 5KB